config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: %i[index show] do
    resources :likes, only: %i[index]
    member do
      get :following, :followers, :map
    end
  end
  resources :relationships, only: %i[create destroy]
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end

  get '/map', to: 'posts#map'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 100 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = current_user.comments.create(content: params[:comment][:content], post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end

  def destroy
    @comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
    @comment_id = @comment.id
    @comment.delete
    @post = Post.find(params[:post_id])
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(post_id: @post.id, id: params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @succeed = false
    flash.now[:success] = "コメントを更新しました。"
    @succeed = true if @comment.update(content: params[:comment][:content])
  end

  private

  def comment_params
    params.require(:comment, :post_id).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
  <div class="comment-list" id="comment_list_<%= comment.id %>">
    <%= image_tag comment.user.profile_image.url, class: "profile-image",size: "50" %>
    <div class="comment-list--item">
      <%= link_to comment.user.name, comment.user, class:"comment-list--item__user-name" %>
      <span class="comment-list--item__date"><%= created_date(comment) %></span>
      <span class="comment-list--item__date" id="is_edited_<%= comment.id %>"><%= edited?(comment) %></span>
      <% if current_user?(comment.user) %>
        <%= button_to "編集", edit_post_comment_path(id: comment.id, post_id: comment.post.id), method: :get, class: "comment-list--item__edit", id: "button_input", remote: true %>
        <%= button_to "削除", post_comment_path(id: comment.id, post_id: comment.post.id), method: :delete, class: "comment-list--item__destroy", id: "button_input", remote: true, data: {confirm: "削除しますか？"}  %>
      <% end %>
      <span id="comment_edit_area_<%= comment.id %>">
        <p><%= comment.content %></p>
      </span>
    </div>
  </div>
  

app/views/comments/_comment_count.html.erb
<%= post.comments.count %>

app/views/comments/_comment_form.html.erb
<%= form_for([post, comment], method: :post, remote: true ) do |f| %>
  <%= f.text_field :content, placeholder: "コメントを残す（100字以内）", class: "post-comment",rows: "1" %>
  <%= f.submit class: "dn" %>
<% end %>

app/views/comments/_count.erb
<%= post.comments.count %>

app/views/comments/_edit_comment_form.html.erb
<span id="comment_edit_area_<%= comment.id %>">
  <%= render 'layouts/error_message', object: comment %>
  <%= form_for([post, comment], method: :patch, remote: true,:url => {:action => :update} ) do |f| %>
    <%= f.text_field :content, value:  comment.content, class: "edit-comment",rows: "1" %>
    <%= f.submit class: "dn" %>
  <% end %>
</span>

app/views/comments/_edit_form.html.erb
<span id="comment_edit_area_<%= comment.id %>">
  <%= render 'layouts/error_message', object: comment %>
  <%= form_for([post, comment], method: :patch, remote: true,:url => {:action => :update} ) do |f| %>
    <%= f.text_field :content, value:  comment.content, class: "edit-comment",rows: "1" %>
    <%= f.submit class: "dn" %>
  <% end %>
</span>

app/views/comments/_form.html.erb
<%= form_for([post, comment], method: :post, remote: true ) do |f| %>
  <%= f.text_field :content, placeholder: "コメントを残す（100字以内）", class: "post-comment",rows: "1" %>
  <%= f.submit class: "dn" %>
<% end %>

app/views/comments/_is_edited.html.erb
<%= edited?(comment) %>

app/views/comments/_update_content.html.erb
<%= render 'layouts/error_message', object: comment %>

<span id="comment_edit_area_<%= comment.id %>">
  <p><%= comment.content %></p>
</span>

app/views/comments/create.js.erb
$("#comments_area").append("<%= j(render 'comments/comment', comment: @comment) %>")
$("#flash-con").html("<%= j(render 'layouts/flash') %>")
$(".count").html("<%= j(render 'comments/count', post: @post ) %>");
$("#comment-error").html("<%= j(render 'layouts/error_message', object: @comment) %>")
$("#comment_content").val('')

app/views/comments/destroy.js.erb
$("#comment_list_<%= @comment.id %>").remove();
$("#flash-con").html("<%= j(render 'layouts/flash') %>");
$(".count").html("<%= j(render 'comments/count', post: @post ) %>");

app/views/comments/edit.js.erb
$("#comment_edit_area_<%= @comment.id %>").replaceWith("<%= j(render 'comments/edit_form', comment: @comment, post: @post) %>");

app/views/comments/update.js.erb
<% if @succeed %>
  $("#comment_edit_area_<%= @comment.id %>").replaceWith("<%= j(render 'comments/update_content', comment: @comment) %>");
  $("#is_edited_<%= @comment.id %>").html("<%= j(render 'comments/is_edited', comment: @comment) %>");
  $("#flash-con").html("<%= j(render 'layouts/flash') %>");
<% else %>
  $("#comment_edit_area_<%= @comment.id %>").replaceWith("<%= j(render 'comments/edit_form', comment: @comment, post: @post) %>");
<% end %>