config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: %i[index show] do
    resources :likes, only: %i[index]
    member do
      get :following, :followers, :map
    end
  end
  resources :relationships, only: %i[create destroy]
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end

  get '/map', to: 'posts#map'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  has_many :posts, dependent: :destroy
  # ProfileImageアップローダーを紐付け
  mount_uploader :profile_image, ProfileImageUploader
  # like関係
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  # rerationship関係
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  # comment
  has_many :comments
  # 足跡関係
  has_many :footprints, dependent: :destroy
  has_many :footprint_posts, through: :footprints, source: :post

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def self.search(search)
    where(['name LIKE ?', "%#{search}%"])
  end

  #  minimagick
  def thumbnail
    variant(resize: '150x150').processed
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_update_path_for(_resource)
    current_user
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :serch
  USER_PER = 12

  def index
    @q = User.ransack(params[:q])
    @users = if params[:q]
               @q.result(distinct: true).order('created_at DESC').page(params[:page]).per(USER_PER)
             else
               User.order('created_at DESC').page(params[:page]).per(USER_PER)
             end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(PER)
    @post_places = @user.posts.select("latitude", "longitude")
    respond_to do |format|
      format.html
      format.js { render 'posts/index' }
    end
  end

  def map
    @user  = User.find(params[:id])
    @posts = @user.posts
    render 'map'
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(USER_PER)
    render 'index'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(USER_PER)
    render 'index'
  end

  private

  def serch
    @q = User.ransack(params[:q])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end

  def user_list_title
    if controller.action_name == "index"
      "ユーザー一覧"
    elsif controller.action_name == "following"
      "フォロー中"
    elsif controller.action_name == "followers"
      "フォローワー"
    end
  end
end

app/views/users/_follow.html.erb
   <%= form_for(current_user.following_relationships.build(following_id: user.id), remote: true) do |f| %>
      <div><%= f.hidden_field :following_id %></div>
      <%= f.submit "フォロー", class: "follow-btn" %>
    <% end %>

app/views/users/_follow_form.html.erb
<div class="follow_form_<%= user.id %>">
 <% unless current_user?(user) || !(user_signed_in?) %>
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user: user%>
  <% else %>
    <%= render 'users/follow', user: user %>
  <% end %>
<% end %>  
</div>

app/views/users/_list.html.erb
  <h3><%= title %></h3>

  <% if users.present? %>
    <ul class="user-list" id="user-list">
      <%= render 'users/pagenate', users: users %>
    </ul>
    <%= link_to_next_page users, 'つづきを見る', remote: true, id: 'more_link' unless users.nil? %>
  <% else %>
    <h4 class="tac">投稿が見つかりませんでした。</h4>
  <% end %>
  

app/views/users/_pagenate.html.erb
  <%= render partial: 'users/user', collection: @users %>

app/views/users/_profile.html.erb
<div class="user-canopy" style='background-image: url("<%= user.profile_image.url %>");'>
  <div class="user-box">
    <%= image_tag(user.profile_image.url, class: "user-box__image profile-image", size: "150") do %>
      <% if current_user?(user) %>
        <%= link_to image_tag("pen.svg", class: "user-box__edit--image"), edit_user_registration_path,class: "user-box__edit" %>
      <% end %>
    <% end %>
  <p class="user-name"><%= user.name %></p>
  <%= render 'users/stats', user: @user %>
  <%= render 'users/follow_form', user: @user %>
  </div>

  <ul class="user-link">
    <li class="user-link__item"><%= link_to "投稿一覧", user %></li>
    <li class="user-link__item"><%= link_to "お気に入り",  user_likes_path(user) %></li>
    <li class="user-link__item"><%= link_to "地図", map_user_path(user) %></li>
    <% if current_user?(user) %>
      <li class="user-link__item"><%= link_to "設定", edit_user_registration_path %></li>
    <% end %>
  </ul>
  </div>

app/views/users/_stats.html.erb
<div class="stats">
  <%= link_to(following_user_path(user), class: "stats-link") do %>
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
    following
  <% end %>
  <%= link_to(followers_user_path(user), class: "stats-link") do %>
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  <% end %>
</div>

app/views/users/_unfollow.html.erb
    <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "フォロー中", class: "follow-btn follow-btn__on" %>
    <% end %>

app/views/users/_user.html.erb
<div class="users-box">
<div class="flex">
  <%= image_tag user.profile_image.url, class: "profile-image", size: "100" %>
  <div class="users-box__profile">

  <p class="users-box__profile__user-name">
  <%= link_to user.name, user %>
  <%= render 'users/follow_form', user: user%>
  </p>
</div>
  </div>
  <div class="users-box__posts">
  <% user.posts.first(4).each do |post| %>
  <%= link_to(post, class: "users-box__posts__link", remote: true,) do %>
    <%= image_tag post.pictures[0].thumb.url, class: "users-box__posts__picture" %>
  <% end %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/serch' %>
<%= render  'profile', user: @user if @user %>
<%= render 'list', users: @users, title: user_list_title %>

app/views/users/index.js.erb
$("#user-list").append("<%= escape_javascript(render partial: 'users/pagenate') %>");
$("#more_link").replaceWith("<%= escape_javascript(link_to_next_page(@users, 'つづきを見る', remote: true, id: 'more_link')) %>");

app/views/users/map.html.erb
  <%= render 'profile', user: @user %>


  <% if @posts.present? %>
    <div class="map-container">
      <div id="user_map" style='width: 100%; height: 600px;'></div>
    </div>
  <% elsif current_user?(@user) %>
  <div class="non-post">
    <h4 class="tac">
    投稿がまだありません。<br>
    最初の投稿をしてみましょう！
    </h4>
    <%= link_to "投稿する", new_post_path, class: "non-post__link" %>
  </div>
  <% else %>
    <h4 class="tac">投稿はまだありません</h4>
  <% end %>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'user_map'}}, function(){
      <% @posts.each do |post| %>
      markers = handler.addMarkers([
      {
          "lat": <%= post.latitude %>,
          "lng": <%= post.longitude %>,
          "infowindow": '<%= image_tag post.pictures[0].thumb.url, class:"gm-post-picture" %><%= link_to "投稿を見る", post, class: "post-link", remote: true %><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{post.latitude},#{post.longitude}&iwloc=J",target: "_blank" %></p>'
      }
      ]);
      <% end %>

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(10);
    });
  </script>

app/views/users/show.html.erb
<div class="user-container">
<%= render 'profile', user: @user %>

<% if @posts.present? %>
  <%= render 'posts/list', title: nil, posts: @posts %>
<% elsif current_user?(@user) %>
<div class="non-post">
  <h4 class="tac">
  投稿がまだありません。<br>
  最初の投稿をしてみましょう！
  </h4>
  <%= link_to "投稿する", new_post_path, class: "non-post__link" %>
</div>
<% else %>
  <h4 class="tac">投稿はまだありません</h4>
<% end %>
</div>