config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: %i[index show] do
    resources :likes, only: %i[index]
    member do
      get :following, :followers, :map
    end
  end
  resources :relationships, only: %i[create destroy]
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end

  get '/map', to: 'posts#map'
end

app/views/layouts/_error_message.html.erb
<% if object.errors.any? %>
  <div class="error-message">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% key = "info" if key == "notice" %>
  <% key = "danger"  if key == "alert" %>
  <%= content_tag :div, value, class: "alert alert-#{key} text-center mb-0" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="footer__item">&copy;2019 photoapp</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="header-logo"><%= link_to "PHOTO APP", root_path %></div>
    <div class="header-menu">
      <ul class="header-list">
          <li class="header-list__item"><%= link_to "トップ", root_path %></li>
          <li class="header-list__item"><%= link_to "すべての投稿", posts_path %></li>
          <li class="header-list__item"><%= link_to "マップで見る", map_path %></li>
          <li class="header-list__item"><%= link_to "すべてのユーザー", users_path %></li>
        <% unless current_user %>
          <li class="header-list__item"><%= link_to "会員登録", new_user_registration_path %></li>
          <li class="header-list__item"><%= link_to "ログイン", new_user_session_path %></li>
        <% else %>
          <li class="header-list__item menu__single">
            <%= link_to current_user.name, current_user, class: "init-button" %>
            <ul class="menu-level">
                <li class="menu-lavel__item"><%= link_to "ユーザーページ", current_user %></li>
                <!--<li class="menu-lavel__item"><a href="#">送受信メッセージ</a></li>-->
                <li class="menu-lavel__item"><%= link_to "各種設定", edit_user_registration_path %></li>
                <li class="menu-lavel__item"><%= link_to "ログアウト", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
          <li class="header-list__item"><%= link_to "投稿する", new_post_path, data: {"turbolinks"=>false} %></li>
        <% end %>
        
      </ul>
    </div>
    <div id="nav-drawer">
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content">
        <ul class="header-list">
          <li class="header-list__item"><%= link_to "トップ", root_path %></li>
          <li class="header-list__item"><%= link_to "すべての投稿", posts_path %></li>
          <li class="header-list__item"><%= link_to "マップで見る", map_path %></li>
          <li class="header-list__item"><%= link_to "すべてのユーザー", users_path %></li>
        <% unless current_user %>
          <li class="header-list__item"><%= link_to "会員登録", new_user_registration_path %></li>
          <li class="header-list__item"><%= link_to "ログイン", new_user_session_path %></li>
        <% else %>
          <div class="header-list__item menu__single">
            <div class="accbox">
              <label class="label" for="label1"><%= current_user.name %></label>
              <input type="checkbox" id="label1" class="cssacc" />
              <div class="accshow">
                <li class="menu-lavel__item"><%= link_to "ユーザーページ", current_user %></li>
                <li class="menu-lavel__item"><%= link_to "各種設定", edit_user_registration_path %></li>
                <li class="menu-lavel__item"><%= link_to "ログアウト", destroy_user_session_path, method: "delete" %></li>
              </div>
            </div>
          </div>
          <li class="header-list__item"><%= link_to "投稿する", new_post_path, data: {"turbolinks"=>false} %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </header>
  <div id="flash-con">
    <%= render 'layouts/flash' %>
  </div>

app/views/layouts/_serch.html.erb
 <div class="search">
  <%= search_form_for @q, class: "search__item" do |f| %>
    <%= f.text_field serch_colmun, placeholder: serch_placeholder, class: "search__item__input" %>
    <%= f.submit "検索", class: "detail" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TRAVEL PHOTO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Varela+Round&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCfc8tByCUMcJJvAYiCgYAn-rXqGcmCIBM"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
    <div id="modal-container"></div>
  </body>
</html>